### ISSUE TITLE
Introduction_to_infrastructure

### ISSUE THREAD

**Issue by DashaVasilyeva** [DashaVasilyeva/educational-project#3]
Time spent on the study of various materials for other issues

**Comment by DashaVasilyeva** [comment]
+ Installation and study of materials on Git - 4 hours
+ Installation of PyCharm and initial acquaintance with this IDE - 2 hours
+ Studying the minidom module API - 30 minutes

**Comment by DashaVasilyeva** [comment]
+ Deleting .idea from all branches in repository - 1,5 hours

**Comment by KulishTanya** [comment]
Установка PyCharm и первоначальное знакомство с этой IDE -2,5 часа
Изучение материалов по Python - 2,5 часа
Установка и изучение материалов по Git - 4 часа

**Comment by DashaVasilyeva** [comment]
+ Remembering SQLite queries - 1 hour
+ Remembering the nuances of using the sqlite module - 2 hours

**Comment by DashaVasilyeva** [comment]
+ Studying `psycopg2` module API - 30 min.
+ Learning PostgreSQL syntax - 1 hour.

**Comment by KulishTanya** [comment]
1.Формирование xml из классов-2,5 часа
2.Заполнение  классов из DBD sqlite-3,5часа

**Comment by DashaVasilyeva** [comment]
+ Learn how to get metadata from MS SQL - 2 hours.
